config/routes.rb
Rails.application.routes.draw do

  get 'welcome/about'
  get 'welcome/commands'
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shop</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>



  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body>

<header>
  <% if signed_in? %>
    Signed in as: <%= current_user.email %>
    <%= button_to 'Sign out', sign_out_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign in', sign_in_path %>
  <% end %>

</header>


<section>
  <div id="flash">
    <% flash.each do |key, value| %>
      <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>
  <%= yield %>

</section>

</body>
</html>

app/views/welcome/about.html.erb
<h1>About Canvas Cacophony</h1>





<h1>About our team</h1>
<div class="list-group">
  <a href="#" class="list-group-item ">
    <h4 class="list-group-item-heading">Jason Schattschneider</h4>
    <p class="list-group-item-text">Major: Computer Engineering</p>

  </a>

  <div class="list-group">
    <a href="#" class="list-group-item ">
      <h4 class="list-group-item-heading">Tanner Barret</h4>
      <p class="list-group-item-text">Major: Computer Science</p>

    </a>

    <div class="list-group">
      <a href="#" class="list-group-item ">
        <h4 class="list-group-item-heading">Austin Borth</h4>
        <p class="list-group-item-text">Major: Computer Science</p>

      </a>

      <div class="list-group">
        <a href="#" class="list-group-item ">
          <h4 class="list-group-item-heading">Cade Nash</h4>
          <p class="list-group-item-text">Major: Computer Engineering</p>

        </a>

        <div class="list-group">
          <a href="#" class="list-group-item ">
            <h4 class="list-group-item-heading">Chris something</h4>
            <p class="list-group-item-text">Major: Computer Science</p>

          </a>

          <div class="list-group">
            <a href="#" class="list-group-item ">
              <h4 class="list-group-item-heading">Ash</h4>
              <p class="list-group-item-text">Major: Computer Science</p>

            </a>


</div>

app/views/welcome/commands.html.erb
<h1>Heres is our list of commands</h1>
<p>These commands can be used in general chat or PM the bot the bot will PM you back with your information.</p>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4,col-xs-6">
    <img src="logos/canvas.png">
  </div>

</div>




<div class="jumbotron">
  <h1>Welcome to Canvas Cacophony!</h1>
  <p>A simple way to interact with Canvas and Discord!</p>



  <p><a class="btn btn-primary btn-lg" <%= link_to "See our about us page", welcome_about_path %></a></p>
  <p><a class="btn btn-primary btn-lg" <%= link_to "See list of commands for bot here!", welcome_commands_path %></a></p>
</div>